import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router';

import Header from '../lib/Header'
import styles from '../styles/Home.module.css'

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>cocagraph</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>cocagraph</h1>
        <p>あなたの最後のデジタルノート</p>

        <div className={styles.grid}>
          <div className={styles.card} onClick={()=>router.push('/account/')}>
            <h3>アカウント作成 &rarr;</h3>
            <p>Googleを通してアカウント作成をすることができます</p>
          </div>
          <div className={styles.card}>
            <h3>アプリについて &rarr;</h3>
            <p>使用法・利用規約等の情報をまとめたNotionページ</p>
          </div>
        </div>
      </main>
    </>
  )
}
